Repository mozilla/fxa-email-service, pull requests merged in 2018-07, with the labels that each got.

#115 feat(docs): generate developer docs with rustdoc
  Cargo.toml
  Dockerfile
  README.md
  r
  scripts/run_queues.sh
  scripts/run_send.sh
  scripts/run_service.sh
  src/app_errors/mod.rs
  src/auth_db/mod.rs
  src/bin/queues.rs
  src/bin/service.rs
  src/bounces/mod.rs
  src/deserialize/mod.rs
  src/duration/mod.rs
  src/lib.rs
  src/logging/mod.rs
  src/message_data/mod.rs
  src/providers/mod.rs
  src/queues/mod.rs
  src/queues/notification.rs
  src/queues/sqs/mod.rs
  src/queues/sqs/notification/mod.rs
  src/send/mod.rs
  src/serialize/mod.rs
  src/settings/mod.rs
  src/validate/mod.rs
Labels: waffle:review

#121 fix(docs): better docs for the settings module
  src/settings/mod.rs
Labels: waffle:review

#120 refactor(types): extract the EmailAddress type to its own module
  src/email_address/mod.rs
  src/email_address/test.rs
  src/lib.rs
  src/send/mod.rs
  src/send/test.rs
  src/settings/mod.rs
Labels: waffle:review

#131 fix(deploy): pin to a known compatible rust version in docker and ci
  .travis.yml
  Cargo.lock
  Dockerfile
  src/settings/mod.rs
Labels: waffle:review

#141 refactor(settings): drop NODE_ENV and add LOG_LEVEL
  Dockerfile
  config/default.json
  config/dev.json
  config/test.json
  scripts/test_standalone.sh
  scripts/test_with_authdb.sh
  src/logging/mod.rs
  src/settings/mod.rs
  src/settings/test.rs
  src/validate/mod.rs
  src/validate/test.rs
Labels: WIP

#142 feat(settings): enable the default provider to override requests
  config/default.json
  config/dev.json
  src/providers/mod.rs
  src/providers/test.rs
  src/send/test.rs
  src/settings/mod.rs
  src/settings/test.rs
Labels: train-118, waffle:review
