Repository mozilla/fxa-email-service, pull requests merged in 2018-06, with the labels that each got.

#39 chore(errors): don't serialize nulls in error payloads
  src/app_errors/mod.rs
Labels: train-114, waffle:review

#37 fix(sendgrid): return message id from the sendgrid provider
  Cargo.lock
  Cargo.toml
  src/providers/mod.rs
  src/providers/sendgrid.rs
  src/queues/sendgrid/mod.rs
  src/send/mod.rs
Labels: train-114, waffle:review

#43 chore(code): eliminate some if-lets in favour of combinators
  src/providers/mod.rs
  src/send/mod.rs
Labels: waffle:review

#55 fix(validation): relax the sendgrid API key validation regex
  src/validate/mod.rs
  src/validate/test.rs
Labels: waffle:review

#58 chore(project): limit futures to < 0.2
  Cargo.lock
  Cargo.toml
Labels: waffle:review

#60 chore(project): remove the validator dependency
  src/send/mod.rs
  src/service_main.rs
Labels: waffle:review

#59 fix(bounces): ensure db errors don't get converted to 429 responses
  src/bounces/mod.rs
  src/bounces/test.rs
Labels: waffle:review

#66 fix(config): inject config in rocket managed state
  Cargo.lock
  src/auth_db/mod.rs
  src/bounces/mod.rs
  src/bounces/test.rs
  src/duration/mod.rs
  src/providers/mod.rs
  src/providers/sendgrid.rs
  src/queues/mod.rs
  src/queues/sqs/mod.rs
  src/send/mod.rs
  src/send/test.rs
  src/service_main.rs
  src/settings/mod.rs
  src/settings/test.rs
Labels: WIP

#78 refactor(project): push core code into a common lib
  Cargo.lock
  Cargo.toml
  src/bin/queues.rs
  src/bin/service.rs
  src/lib.rs
Labels: waffle:review

#80 refactor(db): hide queues db access behind bounces interface
  src/auth_db/mod.rs
  src/bounces/mod.rs
  src/bounces/test.rs
  src/queues/mod.rs
Labels: waffle:review

#72 feat(metadata): store caller-specific metadata with the message id
  .travis.yml
  Cargo.lock
  Cargo.toml
  README.md
  config/default.json
  src/bin/service.rs
  src/deserialize.rs
  src/lib.rs
  src/message_data/mod.rs
  src/message_data/test.rs
  src/send/mod.rs
  src/send/test.rs
  src/settings/mod.rs
  src/settings/test.rs
  src/validate/mod.rs
Labels: waffle:review

#73 feat(metadata): send message metadata in outgoing notifications
  src/message_data/mod.rs
  src/message_data/test.rs
  src/queues/mod.rs
  src/queues/notification.rs
  src/queues/sqs/notification/mod.rs
Labels: waffle:review

#89 feat(providers): add custom headers option
  Cargo.lock
  Cargo.toml
  src/lib.rs
  src/providers/mock.rs
  src/providers/mod.rs
  src/providers/sendgrid.rs
  src/providers/ses.rs
  src/send/mod.rs
Labels: WIP

#94 refactor(errors): use failure crate to handle errors
  src/app_errors/mod.rs
  src/app_errors/test.rs
  src/auth_db/mod.rs
  src/auth_db/test.rs
  src/bin/service.rs
  src/bounces/mod.rs
  src/bounces/test.rs
  src/lib.rs
  src/providers/mock.rs
  src/providers/mod.rs
  src/providers/sendgrid.rs
  src/providers/ses.rs
  src/queues/mod.rs
  src/send/mod.rs
  src/send/test.rs
Labels: waffle:active
